[package]
name = "dustr"
version = "0.1.9"
edition = "2021"

[lib]
name = "dustr"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
walkdir = "2.4"
clap = { version = "4.5", features = ["derive"] }
rayon = "1.10"
jwalk = "0.8"
parking_lot = "0.12"
